import pathlib
import unittest


REPO_ROOT = pathlib.Path(__file__).resolve().parents[1]
CONTROL_CENTER_PATH = REPO_ROOT / "launcher" / "windows" / "control-center.ps1"


class WindowsControlCenterLayoutTests(unittest.TestCase):
    def test_control_center_uses_separate_tools_and_benchmark_tabs(self):
        content = CONTROL_CENTER_PATH.read_text(encoding="utf-8")
        self.assertIn('$toolsTab.Text = "Tools"', content)
        self.assertIn('$benchmarkTab.Text = "Benchmark"', content)
        self.assertIn('$launchPrimaryGroup.Text = "Pokretanje"', content)
        self.assertIn('Start llama.cpp server', content)
        self.assertIn('Stop llama.cpp server', content)
        self.assertIn('Run OpenCode', content)
        self.assertIn('Run llama.cpp web', content)
        self.assertIn('Model browser', content)
        self.assertIn('Test throughput', content)
        self.assertIn('System.Windows.Forms.DataVisualization', content)
        self.assertIn('Refresh-BenchmarkChart', content)
        self.assertIn('IsXValueIndexed = $true', content)
        self.assertIn('Points.AddY', content)
        self.assertIn('AxisLabel = $label', content)
        self.assertIn('ljubicasto = ukupno tok/s kroz regularne zahteve i testove.', content)
        self.assertIn('Dodaj lokalni GGUF', content)
        self.assertIn('Dodaj HF model', content)
        self.assertIn('$browserDownloadStatusBox = New-Object System.Windows.Forms.TextBox', content)
        self.assertIn('Nema aktivnog preuzimanja.', content)
        self.assertIn('$script:BrowserDownloadStatusBox = $browserDownloadStatusBox', content)
        self.assertIn('$script:BrowserSummaryLabel = $summaryLabel', content)
        self.assertIn('function Show-AddHuggingFaceModelDialog', content)
        self.assertIn('$selectBrowserModelById = {', content)
        self.assertIn('Izvor modela: $sourceValue', content)
        self.assertIn('LOKALNI', content)
        self.assertIn('HF', content)
        self.assertIn('$summaryLabel.Text = "Osvezavam model browser..."', content)
        self.assertIn('$summaryLabel.Text = "Aktiviram model $($selected.id)..."', content)
        self.assertIn('$summaryLabel.Text = "Preporuceni model je aktiviran."', content)
        self.assertIn('$summaryLabel.Text = "Poredenje je spremno za model $($selected.id)."', content)
        self.assertIn('Pokrecem Repair install.', content)
        self.assertIn('Pokrecem guided repair:', content)
        self.assertIn("Pokrecem test prompt za profil '$profile'.", content)
        self.assertIn('Pokrecem diagnostics export.', content)
        self.assertIn('Proveravam da li postoji noviji javni release.', content)
        self.assertIn('Pokrecem install update tok.', content)
        self.assertIn('function Get-UsageSourceDisplayName', content)
        self.assertIn('function Format-UsageLabelValue', content)
        self.assertIn('"Izvor: $lastSourceDisplay | Label: $lastLabelDisplay"', content)
        self.assertIn('"Izvori: test $($sourceBreakdown.testPrompt.count)', content)
        self.assertIn("Jos nema benchmark merenja. Pokreni 'Test prompt' ili 'Test throughput'.", content)
        self.assertIn('Pokrecem health akciju: $Name', content)
        self.assertIn('Health akcija je zavrsena: $Name', content)
        self.assertIn('$Name nije uspeo i nije vratio dodatni izlaz.', content)
        self.assertIn('Lokalni status: $(if ($selected.installed) { \'SKINUT\' } else { \'NIJE SKINUT\' })', content)
        self.assertIn('PREPORUCENI FIT', content)
        self.assertIn('if ($selected.recommended -and $selected.fitGroup -eq "canRun")', content)
        self.assertIn('$script:ActiveWorkerName = $null', content)
        self.assertIn('function Update-WorkerHeartbeat', content)
        self.assertIn('radi vec', content)
        self.assertIn('return Join-Path (Get-LocalQwenStateRoot) "state\\agent-launch-settings.json"', content)
        self.assertIn('$installRoot = Get-LocalQwenStateRoot', content)
        self.assertIn('Write-LaunchMessage @("Otvoren install folder: $installRoot")', content)
        self.assertIn('$nextActionBox.ScrollBars = "Vertical"', content)
        self.assertIn('$healthSummaryLabel.Size = New-Object System.Drawing.Size(648, 78)', content)
        self.assertIn('$healthActionPanel.Location = New-Object System.Drawing.Point(18, 136)', content)
        self.assertIn('$healthMeta.Location = New-Object System.Drawing.Point(18, 188)', content)
        self.assertIn('$healthContent.Location = New-Object System.Drawing.Point(18, 304)', content)
        self.assertIn('$diagnosticsMeta.Size = New-Object System.Drawing.Size(648, 124)', content)
        self.assertIn('$diagnosticsContent.Location = New-Object System.Drawing.Point(18, 180)', content)
        self.assertIn('"Public relation: $($latestRelease.versionRelation)"', content)
        self.assertIn('$lines.Add("Lokalni build je noviji od javnog latest release-a.") | Out-Null', content)
        self.assertIn('$lines.Add("Release URL: $($latestRelease.releaseUrl)") | Out-Null', content)
        self.assertIn('"Stanje: $($payload.title)"', content)
        self.assertIn('"Model: $($payload.modelId)"', content)
        self.assertIn('"none" {', content)
        self.assertIn('Sistem izgleda zdravo i trenutno nema potrebe za guided repair korakom.', content)
        self.assertIn('$guidedActionId = if ($payload.primaryAction -and $payload.primaryAction.id) { [string]$payload.primaryAction.id } else { "" }', content)
        self.assertIn('$guidedRepairButton.Enabled = ($guidedActionId -ne "none")', content)
        self.assertIn('$nextActionId = if ($nextAction -and $nextAction.PSObject.Properties["actionId"]) { [string]$nextAction.actionId } else { "" }', content)
        self.assertIn('$isRunnableNextAction = @("repair-install", "start-server", "write-opencode-config", "open-opencode") -contains $nextActionId', content)
        self.assertIn('$runNextActionButton.Enabled = $isRunnableNextAction', content)
        self.assertIn('Sledeci korak trenutno nema pokretljivu akciju: $([string]$nextAction.actionId)', content)


if __name__ == "__main__":
    unittest.main()
